### ISSUE TITLE
Include CSS

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/react-context-tabs#1]
/styles/base.css

``` css

.TabList {
  list-style: none;
  margin: 0;
  padding: 0;
}

.Tab {
  cursor: pointer;
}

.Tab.isDisabled,
.Tab.isSelected {
    cursor: default;
}
```

Can be included by whatever build tool if required.
